services:
  backend:
    build:
      context: ./apps/ENG-Backend
      dockerfile: Dockerfile
    container_name: eng_backend
    restart: unless-stopped
    ports:
      - "2005:2005"
    env_file:
      - ./apps/ENG-Backend/.env
    environment:
      - NODE_ENV=production
    volumes:
      - backend_uploads:/app/files/uploads

  frontend:
    build:
      context: .
      dockerfile: apps/ENG-Frontend/Dockerfile
    container_name: eng_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  backend_uploads: # Volume for persistent backend file uploads (pdf, images, etc.)
