-- Migrate KS400B6 formulas to mtc_formulas table
-- Context vars: idAft, idBf, idBfTolPlus, idBfTolMinus, odBf, odBfTolPlus, odBfTolMinus,
--   wAft, sd, sdCalc, isInner

DELETE FROM mtc_formulas WHERE machine_name = 'KS400B6';

INSERT INTO mtc_formulas (machine_name, tool_category, param_key, formula, description) VALUES

-- WORK DRIVER (wd_*)
('KS400B6', 'workDriver', 'wd_A',  'round((idAft - 1.5) * 10) / 10',          'Work Driver A'),
('KS400B6', 'workDriver', 'wd_B',  'round(sdCalc, 3)',                         'Work Driver B'),
('KS400B6', 'workDriver', 'wd_C',  'round(sdCalc + 2.5)',                      'Work Driver C'),
('KS400B6', 'workDriver', 'wd_D',  '39',                                        'Work Driver D'),
('KS400B6', 'workDriver', 'wd_E',  '45',                                        'Work Driver E'),

-- LOADING CHUTE (lc_*) — lc_D must precede lc_F
('KS400B6', 'loadingChute', 'lc_A',
  'round(219 - (odBf + odBfTolPlus) / 2)',
  'Loading Chute A'),
('KS400B6', 'loadingChute', 'lc_B',
  '(wAft + wAftTolPlus) <= 10 ? 20 : ((wAft + wAftTolPlus) <= 20 ? 30 : ((wAft + wAftTolPlus) <= 30 ? 40 : 50))',
  'Loading Chute B'),
('KS400B6', 'loadingChute', 'lc_C',
  'round(odBf + odBfTolPlus + 0.1, 2)',
  'Loading Chute C'),
('KS400B6', 'loadingChute', 'lc_D',
  'round((wAft + wAftTolPlus + 0.1) * 10) / 10',
  'Loading Chute D'),
('KS400B6', 'loadingChute', 'lc_F',
  'isInner ? "TG" : round(lc_D / 2, 1)',
  'Loading Chute F'),

-- PLUG (plug_*) — plug_A must precede plug_D
('KS400B6', 'plug', 'plug_A',
  'round(idBf + idBfTolMinus - 1, 2)',
  'Plug A'),
('KS400B6', 'plug', 'plug_B',
  'round(wAft - 1.5, 2)',
  'Plug B'),
('KS400B6', 'plug', 'plug_C',
  'sdCalc <= 8 ? round(sdCalc - 0.5, 2) : (sdCalc < 9 ? 8 : round(sdCalc - 0.5, 2))',
  'Plug C'),
('KS400B6', 'plug', 'plug_D',
  'plug_A <= 9 ? 0.5 : 1',
  'Plug D'),

-- WORK GUIDE (wg_*) — wg_A must precede wg_E
('KS400B6', 'workGuide', 'wg_A',
  'round(wAft)',
  'Work Guide A'),
('KS400B6', 'workGuide', 'wg_B',
  'isInner ? round((45 - sdCalc / 2) * 10) / 10 : round((45 - sdCalc / 2 - 1) * 10) / 10',
  'Work Guide B'),
('KS400B6', 'workGuide', 'wg_C',
  'round((odBf + odBfTolPlus + 0.2) * 10) / 10',
  'Work Guide C'),
('KS400B6', 'workGuide', 'wg_D',
  'isInner ? round(((odBf + odBfTolPlus - sdCalc) / 2 + 0.2) * 10) / 10 : 0',
  'Work Guide D (0 means null for outer type)'),
('KS400B6', 'workGuide', 'wg_E',
  'wg_A / 2',
  'Work Guide E'),

-- WORK PUSHER (wp_*) — references idBf+idBfTolMinus directly
('KS400B6', 'workPusher', 'wp_A',
  'round((sdCalc + idBf + idBfTolMinus) / 2, 2)',
  'Work Pusher A'),
('KS400B6', 'workPusher', 'wp_B',
  'round((idBf + idBfTolMinus) / 2, 2)',
  'Work Pusher B'),
('KS400B6', 'workPusher', 'wp_C',
  'floor(((sdCalc <= 20 ? 61.5 : (sdCalc <= 32 ? 71 : 0)) - (idBf + idBfTolMinus) / 2) * 100) / 100',
  'Work Pusher C'),

-- STOCKER CHUTE (sc_*) — only valid when OD_max<=32 && W<=26; adapter guards with base.stockerChute null check
('KS400B6', 'stockerChute', 'sc_A',
  'round((odBf + odBfTolPlus + 0.5) * 10) / 10',
  'Stocker Chute A'),
('KS400B6', 'stockerChute', 'sc_B',
  'round((wAft + 0.5) * 10) / 10',
  'Stocker Chute B'),
('KS400B6', 'stockerChute', 'sc_C',
  'wAft <= 17 ? 22 : (wAft <= 27 ? 32 : 37)',
  'Stocker Chute C'),
('KS400B6', 'stockerChute', 'sc_D',
  'sdCalc <= 6 ? 2 : (sdCalc <= 8 ? 4 : (sdCalc <= 10 ? 6 : 8))',
  'Stocker Chute D'),
('KS400B6', 'stockerChute', 'sc_E',
  'round((wAft + 0.5) / 2, 1)',
  'Stocker Chute E'),

-- FRONT SHOE (fs_*) — fs_A must precede fs_D
('KS400B6', 'frontShoe', 'fs_A',
  'isInner ? 0 : round(wAft / 2 + 2, 2)',
  'Front Shoe A (0 means "Need V" for inner type)'),
('KS400B6', 'frontShoe', 'fs_B',
  '(odBf + odBfTolPlus) < 10 ? 8 : 9',
  'Front Shoe B'),
('KS400B6', 'frontShoe', 'fs_C',  '0.15',   'Front Shoe C'),
('KS400B6', 'frontShoe', 'fs_D',
  'isInner ? 0 : round(31 - (10 - fs_A - 1))',
  'Front Shoe D (0 means "-" for inner type)'),

-- REAR SHOE (rs_*) — rs_B must precede rs_D
('KS400B6', 'rearShoe', 'rs_A',
  'isInner ? 0 : round(wAft / 2 - 2, 2)',
  'Rear Shoe A (0 means "Need X" for inner type)'),
('KS400B6', 'rearShoe', 'rs_B',
  'isInner ? 0 : round(wAft / 2 + 2, 2)',
  'Rear Shoe B (0 means "Need Y" for inner type)'),
('KS400B6', 'rearShoe', 'rs_C',
  '(odBf + odBfTolPlus) < 10 ? 4 : 5',
  'Rear Shoe C'),
('KS400B6', 'rearShoe', 'rs_D',
  'isInner ? 0 : (rs_B < 7.5 ? 30 : 0)',
  'Rear Shoe D (0 means null)'),

-- PILOT PIN (pp_*) — pp_A must precede pp_D, pp_E; pp_B must precede pp_F
('KS400B6', 'pilotPin', 'pp_Type',
  '(idBf + idBfTolMinus) < 6 ? "TYPE1" : ((idBf + idBfTolMinus) < 10 ? "TYPE2" : "TYPE3")',
  'Pilot Pin Type'),
('KS400B6', 'pilotPin', 'pp_A',
  'pp_Type == "TYPE1" ? floor(((idBf + idBfTolMinus) - 0.5) * 10) / 10 : floor(((idBf + idBfTolMinus) - 1.0) * 10) / 10',
  'Pilot Pin A'),
('KS400B6', 'pilotPin', 'pp_B',
  'pp_Type == "TYPE1" ? round((wAft + 1.5) * 10) / 10 : (pp_Type == "TYPE2" ? round((wAft + 2.5) * 10) / 10 : round((wAft + 2.0) * 10) / 10)',
  'Pilot Pin B'),
('KS400B6', 'pilotPin', 'pp_C',
  'pp_Type == "TYPE1" ? floor(((idBf + idBfTolMinus) - 1.0) * 10) / 10 : floor(((idBf + idBfTolMinus) - 1.5) * 10) / 10',
  'Pilot Pin C'),
('KS400B6', 'pilotPin', 'pp_D',
  'pp_Type == "TYPE3" ? 0 : floor((wAft - 1) * 10) / 10',
  'Pilot Pin D (0 means "-" for TYPE3)'),
('KS400B6', 'pilotPin', 'pp_E',
  'pp_Type == "TYPE1" ? 6 : (pp_Type == "TYPE2" ? 9 : pp_C)',
  'Pilot Pin E'),
('KS400B6', 'pilotPin', 'pp_F',
  'round((pp_B + 5) * 10) / 10',
  'Pilot Pin F'),
('KS400B6', 'pilotPin', 'pp_G',
  'wAft < 18 ? 48 : 65',
  'Pilot Pin G'),
('KS400B6', 'pilotPin', 'pp_H',  '2.0',   'Pilot Pin H'),
('KS400B6', 'pilotPin', 'pp_J',
  'pp_Type == "TYPE1" ? 4.1 : 4.0',
  'Pilot Pin J'),
('KS400B6', 'pilotPin', 'pp_K',
  'pp_J + 1',
  'Pilot Pin K'),
('KS400B6', 'pilotPin', 'pp_L',
  'pp_Type == "TYPE1" ? "R1" : "R2"',
  'Pilot Pin L');
