/**
 * useXmlParser — Custom React Hook for XML Metadata Parsing
 * 
 * Fetches an XML file from a URL, parses it into a structured JSON object
 * using the browser's native DOMParser (no dependency needed).
 * Designed for the CATIA metadata XML generated by catia_controller.py.
 */
import { useState, useEffect, useCallback } from 'react';

/**
 * Parse an XML string into a nested JSON object
 */
function xmlToJson(xmlString) {
  const parser = new DOMParser();
  const xmlDoc = parser.parseFromString(xmlString, 'text/xml');

  // Check for parsing errors
  const parseError = xmlDoc.querySelector('parsererror');
  if (parseError) {
    throw new Error(`XML parsing error: ${parseError.textContent}`);
  }

  return elementToJson(xmlDoc.documentElement);
}

/**
 * Recursively convert an XML element to a JSON object
 */
function elementToJson(element) {
  const result = {};

  // Collect attributes
  if (element.attributes && element.attributes.length > 0) {
    result._attributes = {};
    for (const attr of element.attributes) {
      result._attributes[attr.name] = attr.value;
    }
  }

  // Collect children
  const children = element.children;
  if (children.length === 0) {
    // Leaf node — return text content
    const text = element.textContent.trim();
    if (result._attributes) {
      result._text = text;
      return result;
    }
    return text || '';
  }

  for (const child of children) {
    const childName = child.tagName;
    const childValue = elementToJson(child);

    if (result[childName] !== undefined) {
      // Multiple children with same tag → array
      if (!Array.isArray(result[childName])) {
        result[childName] = [result[childName]];
      }
      result[childName].push(childValue);
    } else {
      result[childName] = childValue;
    }
  }

  return result;
}

/**
 * Extract title block data from parsed XML metadata
 */
function extractTitleBlock(parsedXml) {
  if (!parsedXml) return {};

  const titleBlock = parsedXml.TitleBlock || {};
  const partInfo = parsedXml.PartInfo || {};

  return {
    partNumber: partInfo.PartNumber || '',
    partName: partInfo.Name || '',
    revision: partInfo.Revision || 'A',
    scale: titleBlock.Scale || '1:1',
    sheet: titleBlock.Sheet || '1/1',
    drawingSize: titleBlock.DrawingSize || 'A4',
    material: titleBlock.Material || '',
    weight: titleBlock.Weight || '',
    tolerance: titleBlock.Tolerance || 'ISO 2768-mK',
    drawnBy: titleBlock.DrawnBy || '',
    checkedBy: titleBlock.CheckedBy || '',
    approvedBy: titleBlock.ApprovedBy || '',
    date: titleBlock.Date || new Date().toISOString().split('T')[0]
  };
}

/**
 * Extract parameter list from parsed XML metadata
 */
function extractParameters(parsedXml) {
  if (!parsedXml || !parsedXml.Parameters) return [];

  const paramsNode = parsedXml.Parameters;
  let paramList = paramsNode.Parameter || [];

  if (!Array.isArray(paramList)) {
    paramList = [paramList];
  }

  return paramList.map((p, index) => ({
    key: index,
    name: p?._attributes?.name || `param_${index}`,
    value: p?._attributes?.value || p?._attributes?.new || '',
    old: p?._attributes?.old || '',
    unit: (p?._attributes?.name || '').match(/\(([^)]+)\)/)?.[1] || ''
  }));
}

/**
 * Custom hook: useXmlParser
 * 
 * @param {string} url - URL to fetch XML from
 * @param {Object} options - { autoFetch: true, rawXml: null }
 * @returns {{ data, titleBlock, parameters, loading, error, refetch }}
 */
export default function useXmlParser(url, options = {}) {
  const { autoFetch = true, rawXml = null } = options;

  const [data, setData] = useState(null);
  const [titleBlock, setTitleBlock] = useState({});
  const [parameters, setParameters] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const parseAndSet = useCallback((xmlString) => {
    try {
      const parsed = xmlToJson(xmlString);
      setData(parsed);
      setTitleBlock(extractTitleBlock(parsed));
      setParameters(extractParameters(parsed));
      setError(null);
    } catch (e) {
      setError(e.message);
    }
  }, []);

  const fetchXml = useCallback(async (fetchUrl) => {
    const targetUrl = fetchUrl || url;
    if (!targetUrl) return;

    setLoading(true);
    setError(null);

    try {
      const response = await fetch(targetUrl);
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }
      const xmlText = await response.text();
      parseAndSet(xmlText);
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  }, [url, parseAndSet]);

  // Auto-fetch on mount or URL change
  useEffect(() => {
    if (autoFetch && url) {
      fetchXml();
    }
  }, [url, autoFetch, fetchXml]);

  // Parse raw XML if provided
  useEffect(() => {
    if (rawXml) {
      parseAndSet(rawXml);
    }
  }, [rawXml, parseAndSet]);

  return {
    data,
    titleBlock,
    parameters,
    loading,
    error,
    refetch: fetchXml
  };
}
