/**
 * Fanuc post-processor — toolpath operations out to an NC program.
 *
 * This is the last stage, and the one that closes the loop the whole CAM side
 * is verified by: the text it produces is fed straight back through
 * `engine/gcode/interpreter.js`, and the segments that come out must retrace
 * the moves that went in. A post is normally the least testable part of a CAM
 * system; here it is the most, because the reader already existed.
 *
 * Two conventions are the post's business alone, not the geometry's:
 *
 * - **Diameter mode.** Turning moves carry radii. Fanuc lathes are programmed
 *   on diameter, so X is doubled on the way out unless told otherwise.
 * - **Constant surface speed.** Lathes get `G96` with a `G50` clamp rather than
 *   a fixed RPM, because the correct spindle speed changes with the diameter
 *   being cut. Mills get a plain `G97`-style `S`.
 *
 * Output is modal: a word is emitted only when it changes, which is what makes
 * the file readable at the machine.
 *
 * The control-specific wrapping — tape marks, comment character, how the
 * machine goes home, whether it has a tool changer at all — is **not** decided
 * here. It comes in as a `dialect` from `dialect.js`, chosen by the machine the
 * operator picked. This file writes ISO motion; the dialect says how the
 * particular control likes it packaged. Fanuc remains the default, which is why
 * the file keeps its name.
 *
 * Pure string building. No React, no store, no DOM.
 */

import { dialectFor, programHeader } from './dialect.js';

/**
 * Fanuc number format: always a decimal point, because a bare `X10` is read as
 * 10 *microns* on controls still in incremental-decimal mode. `X10.` is
 * unambiguous everywhere.
 */
function num(v, decimals = 3) {
  const r = Number(v.toFixed(decimals));
  return Number.isInteger(r) ? `${r}.` : String(r);
}

/** Emit a block, tracking modal state so unchanged words are dropped. */
class Writer {
  constructor(opts = {}) {
    this.lines = [];
    this.state = { g: null, x: null, y: null, z: null, a: null, f: null, s: null };
    this.blockNumbers = opts.blockNumbers ?? false;
    this.dialect = opts.dialect ?? dialectFor();
    this.n = 10;
  }

  raw(text) {
    this.lines.push(text);
    return this;
  }

  comment(text) {
    // Parentheses are the comment delimiter, so they cannot appear inside one.
    const body = String(text).replace(/[()]/g, '');
    return this.raw(this.dialect.commentStyle === 'semicolon' ? `; ${body}` : `(${body})`);
  }

  /** Several blocks at once — a dialect's safe-start or homing sequence. */
  block(lines) {
    for (const line of lines || []) this.raw(line);
    return this;
  }

  blank() { return this.raw(''); }

  /** A motion block. Words equal to the current modal value are omitted. */
  move({ g, x, y, z, a, f }) {
    const parts = [];
    if (g != null && g !== this.state.g) { parts.push(g); this.state.g = g; }
    const axis = (word, value, key) => {
      if (value == null) return;
      if (this.state[key] != null && Math.abs(this.state[key] - value) < 1e-6) return;
      parts.push(`${word}${num(value)}`);
      this.state[key] = value;
    };
    axis('X', x, 'x');
    axis('Y', y, 'y');
    axis('Z', z, 'z');
    // A rotary index. It is modal like any other axis, so a run of operations
    // at the same angle writes it once — which is also what makes it obvious in
    // the file where the table actually turns.
    axis('A', a, 'a');
    if (f != null && f !== this.state.f) { parts.push(`F${num(f, 4)}`); this.state.f = f; }
    if (parts.length === 0) return this;
    const body = parts.join(' ');
    return this.raw(this.blockNumbers ? `N${(this.n += 10)} ${body}` : body);
  }

  /** A non-motion block; invalidates nothing but is still tracked for F and S. */
  code(text) { return this.raw(text); }

  /** Forget modal position — used after a tool change, where position is unknown. */
  resetPosition() {
    this.state.x = this.state.y = this.state.z = null;
    this.state.g = null;
    return this;
  }

  toString() { return this.lines.join('\n'); }
}

const HEADER_WARNING = [
  'GENERATED BY CAM-WEB - VERIFY BEFORE CUTTING',
  'SPEEDS AND FEEDS ARE STARTING POINTS ONLY',
  'NO COLLISION OR HOLDER CHECK WAS PERFORMED',
  'DRY RUN WITH THE TOOL CLEAR OF THE PART FIRST',
];

/**
 * Post a turning program.
 *
 * @param {{name?:string, number?:number, operations:object[], stock:object}} program
 * @param {{diameterMode?:boolean, safeX?:number, safeZ?:number}} opts
 */
export function postTurning(program, opts = {}) {
  const {
    diameterMode = true, blockNumbers = false,
    programNumber = 1, controller, dialect = dialectFor(controller),
  } = opts;
  const coolant = (opts.coolant ?? true) && dialect.coolant;
  const w = new Writer({ blockNumbers, dialect });
  const xOut = (r) => (diameterMode ? r * 2 : r);

  if (dialect.tapeMarks) w.raw('%');
  const header = programHeader(dialect, programNumber, program.name);
  if (header) w.raw(header);
  else w.comment(String(program.name || 'PART').toUpperCase());
  for (const line of HEADER_WARNING) w.comment(line);
  if (program.machineLabel) w.comment(`MACHINE: ${program.machineLabel.toUpperCase()}`);
  if (dialect.caveat) w.comment(dialect.caveat);
  if (program.material) w.comment(`MATERIAL: ${program.material.toUpperCase()}`);
  if (program.stock) {
    w.comment(`STOCK: BAR DIA ${num(program.stock.radius * 2, 2)} X ${num((program.stock.zMax ?? 0) - (program.stock.zMin ?? 0), 2)} LONG`);
  }
  w.comment(diameterMode ? 'X IS DIAMETER' : 'X IS RADIUS');
  w.blank();
  // Metric, no nose-radius comp, feed per revolution, ZX plane — spelled the
  // way this control spells it.
  w.block(dialect.turnSafeStart);
  w.block(dialect.turnHome);

  let toolNo = 0;
  for (const op of program.operations) {
    toolNo++;
    w.blank();
    w.comment(`OP${toolNo}: ${op.name.toUpperCase()}`);
    w.comment(`TOOL: ${op.tool.label.toUpperCase()}`);
    for (const note of op.notes || []) w.comment(note.toUpperCase());
    // T0101 — offset number conventionally mirrors the turret station.
    if (dialect.toolChanges) w.code(`T${String(toolNo).padStart(2, '0')}${String(toolNo).padStart(2, '0')}`);
    w.code(`G50 S${op.speeds.clampRpm}`);
    w.code(`G96 S${op.speeds.vc} M03`);
    if (coolant) w.code('M08');
    w.resetPosition();

    for (const m of op.moves) {
      w.move({
        g: m.t === 'rapid' ? 'G00' : 'G01',
        x: xOut(m.x),
        z: m.z,
        f: m.t === 'feed' ? op.speeds.fn : null,
      });
    }

    if (coolant) w.code('M09');
    w.block(dialect.turnHome);
  }

  w.blank();
  w.code('M05');
  w.code(dialect.programEnd);
  if (dialect.tapeMarks) w.raw('%');
  return w.toString();
}

/**
 * Post a milling program.
 *
 * Tool length compensation is applied on the first approach to Z (`G43 H..`),
 * and cancelled with `G49` at the end — leaving it active is one of the classic
 * ways to crash the next job.
 */
export function postMilling(program, opts = {}) {
  const {
    blockNumbers = false, programNumber = 1,
    safeZ = 50, workOffset = 'G54',
    controller, dialect = dialectFor(controller),
  } = opts;
  const coolant = (opts.coolant ?? true) && dialect.coolant;
  const w = new Writer({ blockNumbers, dialect });

  if (dialect.tapeMarks) w.raw('%');
  const header = programHeader(dialect, programNumber, program.name);
  if (header) w.raw(header);
  else w.comment(String(program.name || 'PART').toUpperCase());
  for (const line of HEADER_WARNING) w.comment(line);
  if (program.machineLabel) w.comment(`MACHINE: ${program.machineLabel.toUpperCase()}`);
  if (dialect.caveat) w.comment(dialect.caveat);
  if (program.material) w.comment(`MATERIAL: ${program.material.toUpperCase()}`);
  if (program.stock) {
    const s = program.stock;
    w.comment(`STOCK: ${num(s.sizeX, 2)} X ${num(s.sizeY, 2)} X ${num(s.sizeZ, 2)}`);
  }
  w.blank();
  // XY plane, comps off, no canned cycle, absolute — as this control spells it.
  w.block(dialect.millSafeStart);

  let toolNo = 0;
  for (const op of program.operations) {
    toolNo++;
    w.blank();
    w.comment(`OP${toolNo}: ${op.name.toUpperCase()}`);
    w.comment(`TOOL: T${toolNo} ${op.tool.label.toUpperCase()}`);
    for (const note of op.notes || []) w.comment(note.toUpperCase());
    if (dialect.toolChanges) w.code(`T${toolNo} M06`);
    w.code(`S${op.speeds.rpm} M03`);
    if (dialect.workOffset) w.code(workOffset);
    if (coolant) w.code('M08');
    w.resetPosition();

    // Index the rotary before anything approaches the part. This sits after
    // the tool change — where the spindle is at its home position and nothing
    // is near the work — because turning a table with the cutter down in a
    // pocket is the classic way to destroy both.
    if (op.indexA != null) {
      if (dialect.rotary) w.move({ g: 'G00', a: op.indexA });
      else w.comment(`INDEX TO A${op.indexA} BY HAND - THIS CONTROL HAS NO ROTARY`);
    }

    const first = op.moves[0];
    if (first) {
      w.move({ g: 'G00', x: first.x, y: first.y });
      if (dialect.toolLengthComp) {
        w.code(`G43 H${toolNo} Z${num(safeZ)}`);
        w.state.z = safeZ;
      } else {
        w.move({ g: 'G00', z: safeZ });
      }
    }

    for (const m of op.moves) {
      if (m.cycle) { // drilling: emit a canned cycle instead of point moves
        w.code(cannedCycle(m, op));
        continue;
      }
      w.move({
        g: m.t === 'rapid' ? 'G00' : 'G01',
        x: m.x, y: m.y, z: m.z,
        f: m.t === 'feed' ? op.speeds.feed : null,
      });
    }

    w.move({ g: 'G00', z: safeZ });
    if (coolant) w.code('M09');
    w.code('M05');
  }

  w.blank();
  if (dialect.toolLengthComp) w.code('G49');
  w.block(dialect.millHome);
  w.code(dialect.programEnd);
  if (dialect.tapeMarks) w.raw('%');
  return w.toString();
}

/** A drilling block: G81 straight, or G83 pecking when the hole is deep. */
function cannedCycle(m, op) {
  const parts = [m.cycle, `X${num(m.x)}`, `Y${num(m.y)}`, `Z${num(m.z)}`, `R${num(m.r ?? 2)}`];
  if (m.cycle === 'G83' && m.peck) parts.push(`Q${num(m.peck)}`);
  parts.push(`F${num(op.speeds.feed, 1)}`);
  return parts.join(' ');
}

/** Dispatch on the program's machine mode. */
export function post(program, opts = {}) {
  return program.mode === 'turn' ? postTurning(program, opts) : postMilling(program, opts);
}
